if __name__ == '__main__':
    stv = Stvorce(2)
    print(f'{stv.pocet() = }')
    print(f'{stv.zhusti() = }')
    print(stv)
    print(f'{stv.urob('23') = }')
    print(stv)
    print(f'{stv.pocet() = }')
    print(f'{stv.zhusti() = }')
    print(f'{stv.urob(('2', '3')) = }')
    print(stv)
    print(f'{stv.pocet() = }')
    print(f'{stv.zhusti() = }')