class Stvorce:
    def __init__(self, n):
        ...

    def urob(self, index):
        ...

    def pocet(self):
        ...

    def __repr__(self):
        ...

    def zhusti(self):
        ...