if __name__ == '__main__':
    k = RobotKarel('subor1.txt')
    print(f'{k.robot = }')
    k.robot = (0, 0, 0)
    print(k)
    print(f'{k.rob('krok') = }')
    print(f'{k.rob('2 zdvihni') = }')
    k.rob('krok')
    k.rob('vpravo')
    k.rob('krok')
    k.rob('2 zdvihni')
    k.rob('2 krok')
    print(k)
    print(f'{k.batoh = }')
    k.rob('poloz vlavo')
    k.rob('krok 6 vlavo')
    print(k)
    print(f'{k.robot = }')
    print(f'{k.batoh = }')