>>> vek.keys()
    dict_keys(['Jan', 'Hana', 'Maria', 'Ema'])
>>> vek.values()
    dict_values([19, 16, 17, 19])
>>> vek.items()
    dict_items([('Jan', 19), ('Hana', 16), ('Maria', 17), ('Ema', 19)])