SIN
                                         SIN
                                              SIN
                                                    SIN
                                                         SIN
                                                             SIN
                                                                 SIN
                                                                   SIN
                                                                     SIN
                                                                      SIN
                                                                     SIN
                                                                   SIN
                                                                 SIN
                                                             SIN
                                                         SIN
                                                    SIN
                                              SIN
                                         SIN
                                   SIN
                            SIN
                       SIN
                 SIN
            SIN
        SIN
    SIN
  SIN
SIN
SIN
SIN
  SIN
    SIN
        SIN
            SIN
                 SIN
                       SIN
                            SIN
                                  SIN