if __name__ == '__main__':
    m = Mravec('subor1.txt')
    print(m)
    print(f'{m.zisti() = }')
    print(f'{m.start(1, 0) = }')
    print(f'{m.rob('pp') = }')
    print(m)
    print(f'{m.zisti() = }')
    print(f'{m.rob('dlll') = }')
    print(m)
    print(f'{m.zisti() = }')