>>> a = '7 3'
>>> ...
    ValueError: ...
>>> ...
    TypeError: ...
>>> ...
    FileNotFoundError: ...
>>> ...
    ZeroDivisionError: ...
>>> ...
    AttributeError: ...
>>> ...
    NameError: ...
>>> ...
    AssertionError: ...
>>> ...
    OverflowError: ...