>>> 1 + '2'
    ...
    TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>> 12 / 0
    ...
    ZeroDivisionError: division by zero
>>> x+1
    ...
    NameError: name 'x' is not defined
>>> open('')
    ...
    FileNotFoundError: [Errno 2] No such file or directory: ''
>>> [1,2,3][10]
    ...
    IndexError: list index out of range
>>> 5()
    ...
    TypeError: 'int' object is not callable
>>> ''.x
    ...
    AttributeError: 'str' object has no attribute 'x'
>>> 2 ** 10000 / 1.
    ...
    OverflowError: int too large to convert to float
>>> import x
    ...
    ImportError: No module named 'x'
>>> def t(): x += 1
>>> t()
    ...
    UnboundLocalError: local variable 'x' referenced before assignment